#!/usr/bin/expect
set timeout -1
set ip [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set passwd [lindex $argv 3]
spawn ssh -p $port $user@$ip
expect {
  "yes/no"
  {send "yes\r"; exp_continue;}
  "password:"
  {send "$passwd\r"; exp_continue;}
  "Last login"
  {send "sudo sh -c 'su - root'\r"; exp_continue;}
  "password for"
  {send "$passwd\r"; exp_continue;}
  "/root"
  {send "cd /home/$user/\rbash /home/$user/node_init.sh.confed\r"; set timeout 0;}
}
expect eof
interact
