apiVersion: v1
kind: Pod
metadata:
  name: apiserver
  labels:
    name: apiserver
spec:
  containers:
  - command:
    - sh
    - -c
    - 'kube-apiserver --insecure-bind-address=bind_ip --insecure-port=8080 --etcd-servers=http://host_ip:2379 --service-cluster-ip-range=10.10.10.0/24 --admission-control=NamespaceLifecycle,LimitRanger,ResourceQuota --logtostderr=false --log-dir=/home/k8s-t/log/kubernets &> /var/log/apiserver.log'
    name: kube-apiserver
    image: docker.io/kube-apiserver:1.10
    volumeMounts:
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /home/log/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true