apiVersion: v1
kind: Pod
metadata:
  name: cm
  labels:
    name: cm
spec:
  containers:
  - command:
    - sh
    - -c
    - "kube-controller-manager --master=http://10.13.130.78:8080 &> /var/log/cm.log"
    name: kube-apiserver
    image: docker.io/kube-cm:1.10
    volumeMounts:
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /home/log/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true