apiVersion: v1
kind: Pod
metadata:
  name: etcd
  labels:
    name: etcd
spec:
  containers:
  - command:
    - sh
    - -c
    - "source /etc/conf/etcd.conf && etcd $ARGS >> /var/log/etcd.log 2>&1"
    name: etcd
    image: docker.io/etcd:3.2
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
  - hostPath:
      path: /home/log/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true