apiVersion: v1
kind: Pod
metadata:
  name: etcd
  labels:
    name: etcd
spec:
  containers:
  - command:
    - sh
    - -c
    - "etcd  --advertise-client-urls=$ADVERTISE_CLIENT_URLS --listen-client-urls=$LISTEN_CLIENT_URLS --data-dir=$DATA_DIR >> /var/log/etcd.log 2>&1"
    name: etcd
    image: docker.io/etcd:3.2
    env:
    - name: ADVERTISE_CLIENT_URLS
      value: http://host_ip:2379
    - name: LISTEN_CLIENT_URLS
      value: http://0.0.0.0:2379
    - name: DATA_DIR
      value: /var/lib/etcd
    volumeMounts: 
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
  - hostPath:
      path: /var/log/kubernetes/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true