apiVersion: v1
kind: Pod
metadata:
  name: cm
  labels:
    name: cm
spec:
  containers:
  - command:
    - sh
    - -c
    - "kube-controller-manager --master=http://host_ip:8080 >> /var/log/cm.log 2>&1"
    name: kube-cm
    image: docker.io/kube-controller-manager:1.10
    volumeMounts:
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /home/log/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true