apiVersion: v1
kind: Pod
metadata:
  name: apiserver
  labels:
    name: apiserver
spec:
  containers:
  - command:
    - sh
    - -c
    - 'kube-apiserver --insecure-bind-address=0.0.0.0 --insecure-port=8080 --etcd-servers=http://host_ip:2379 --service-cluster-ip-range=cluster_ip_range/24 --admission-control=NamespaceLifecycle,LimitRanger,ResourceQuota  2>&1 > /var/log/apiserver.log'
    name: kube-apiserver
    image: docker.io/kube-apiserver:1.10
    volumeMounts:
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /home/log/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true