apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  labels:
    name: kube-scheduler
spec:
  containers:
  - command:
    - sh
    - -c
    - "kube-scheduler --master=http://host_ip:8080 >> /var/log/kube-scheduler.log 2>&1"
    name: kube-scheduler
    image: docker.io/kube-scheduler:1.10
    volumeMounts:
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /var/log/kubernetes/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true