apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  labels:
    name: kube-apiserver
spec:
  containers:
  - command:
    - sh
    - -c
    - 'kube-apiserver --insecure-bind-address=0.0.0.0 --insecure-port=8080 --etcd-servers=http://host_ip:2379 --service-cluster-ip-range=cluster_ip_range/24 --admission-control=NamespaceLifecycle,LimitRanger,ResourceQuota >> /var/log/kube-apiserver.log 2>&1'
    name: kube-apiserver
    image: docker.io/kube-apiserver:1.10
    volumeMounts:
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /var/log/kubernetes/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true