apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  labels:
    name: kube-controller-manager
spec:
  containers:
  - command:
    - sh
    - -c
    - "source /etc/conf/kube-controller-manager.conf && kube-controller-manager $ARGS >> /var/log/cm.log 2>&1"
    name: kube-cm
    image: docker.io/kube-controller-manager:1.10
    volumeMounts:
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /home/log/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true