apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  labels:
    name: kube-controller-manager
spec:
  containers:
  - command:
    - sh
    - -c
    - "kube-controller-manager --master=http://host_ip:8080 >> /var/log/kube-controller-manager.log 2>&1"
    name: kube-cm
    image: docker.io/kube-controller-manager:1.10
    volumeMounts:
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /var/log/kubernetes/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true