apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    name: proxy
spec:
  containers:
  - command:
    - sh
    - -c
    - "kube-proxy --master=http://host_ip:8080 --hostname-override=host_name --logtostderr=true --log-dir=/var/log/kubernetes --v=4 2>&1 > /var/log/proxy.log"
    name: kube-proxy
    image: docker.io/kube-proxy:1.10
    volumeMounts:
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /home/log/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true