apiVersion: v1
kind: Pod
metadata:
  name: scheduler
  labels:
    name: scheduler
spec:
  containers:
  - command:
    - sh
    - -c
    - "kube-scheduler --master=http://10.13.130.78:8080 &> /var/log/scheduler.log"
    name: kube-scheduler
    image: docker.io/kube-sch:1.10
    volumeMounts:
    - mountPath: /var/log/
      name: log
  volumes:
  - hostPath:
      path: /home/log/
      type: DirectoryOrCreate
    name: log
  hostNetwork: true